[tool.poetry]
name = "zearch"
version = "0.1.0"
description = "Zendesk Search Code Challenge"
authors = ["Chris Rode"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
